version: "2"
services:
  backend:
    container_name: backEnd
    environment:
      - DOCKER=true
      - mongoUrl=mongodb://mongo:27017/azuredevopsbi
    restart: always
    build: .\backEnd
    volumes:
      - ./backend:/usr/src/app
      - ./backend/node_modules:/usr/src/app/node_modules
    ports:
      - "10010:10010"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
  frontend:
    container_name: frontEnd
    environment:
      - DOCKER=true
      - REACT_APP_URL=${ROOT_URL}
      - REACT_APP_APIKEY=${PAT}
    restart: always
    build: .\frontEnd
    volumes:
      - ./frontEnd:/usr/src/app
      - ./frontEnd/node_modules:/usr/src/app/node_modules
    ports:
      - "3000:3000"
      - "35729:35729"
    links:
      - backend
