version: "2"
services:
  backend:
    container_name: backEnd
    restart: always
    build: .\backEnd
    ports: 
      - "4000:4000"
    links: 
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes: 
      - ./data:/data/db
    ports:
      - "27017:27017"
  frontend:
    container_name: frontEnd
    restart: always
    build: .\frontEnd
    ports: 
      - "3000:3000"
    links: 
      - backend